// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/form": {
    params: {};
  };
  "/end": {
    params: {};
  };
  "/test": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/form" | "/end" | "/test";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/form.jsx": {
    id: "routes/form";
    page: "/form";
  };
  "routes/end.jsx": {
    id: "routes/end";
    page: "/end";
  };
  "routes/arduinoTest.jsx": {
    id: "routes/arduinoTest";
    page: "/test";
  };
};